web:
  image: grzegorzwodo/seqr-ecommerce-base:PHP5_6
  container_name: woocommerce_seqr_container
  ports:
    - "8080:80"
    - "3306:3306"
  volumes_from:
    - web-data
web-data:
  image: mosyda/ecommerce-woocommerce-data
  volumes:
    - $WC_SEQR_PLUGIN_DIR:/var/www/html/wp-content/plugins/seqr
